x = str("Hello, KBTU!")
x = int(27)
x = float(27.48)
x = complex(1j)
x = list(("films", "series", "shows"))
x = tuple(("films", "series", "shows"))
x = range(6)
x = dict(name = "alina", age = 18)
x = set(("films", "series", "shows"))
x = frozenset(("films", "series", "shows"))
x = bool(5)
x = bytes(5)
x = bytearray(5)
x = memoryview(bytes(5))